version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: gabrielcasado
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: echo "hello world"
