version: 2.1
jobs:
  build:
    docker:
      - image: gabrielcasado/flutter
        auth:
          username: gabrielcasado
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: flutter test
